Add iceUseIpv4/6 config to RTCPeerConnection
shinyoshiaki/werift-webrtc pull request #252
Opened 2022-08-31 21:11 UTC by oeed

With support for using specific interfaces/addresses in #249, if one of the given family addresses is undefined it'll automatically pick one. In some situations this is undesirable and it's instead preferred to not use that family. For example, if wanting to use `eth1`, but it only has an IPv4 address, giving `undefined` for `udp6` address will result in it picking the default address (from, say, `eth0`). In such situations it's desirable to give the ability to disable IPv6.

The underlying connection already has support for `useIpv4`/`useIpv6`, this simply exposes it at the `RTCPeerConnection` level.

2022-09-04 10:14 UTC, shinyoshiaki requested changes

2022-09-04 10:14 UTC, shinyoshiaki commented on packages/webrtc/src/peerConnection.ts
> +  iceUseIpv4: undefined,
Set the default value to true

2022-09-04 10:14 UTC, shinyoshiaki commented on packages/webrtc/src/peerConnection.ts
> +  iceUseIpv6: undefined,
Set the default value to true

2022-09-12 21:19 UTC, oeed commented
Sorry for delay, fixed.

2022-09-15 09:37 UTC, merged