Add iceAdditionalHostAddresses
shinyoshiaki/werift-webrtc pull request #258
Opened 2022-09-21 03:51 UTC by oeed

This adds an optional config array to specify host addresses to be used in `gatherCandidates`. Any addresses will be prepended on to the address array and candidates found for it.

We found this necessary as the candidate we need to use is both a `utun` interface and a loopback address, which `nodeIpAddress` explicitly filters out. Alternatively, this could be changed to modify what `nodeIpAddress` filters, but thought this would be more flexible. Happy to modify.

2022-09-25 07:24 UTC, shinyoshiaki requested changes

2022-09-25 07:24 UTC, shinyoshiaki commented on packages/ice/src/ice.ts
> +        address = uniq([...this.options.additionalHostAddresses, ...address]);
It seems to me that it would be better to use Set instead of uniq

2022-09-26 20:33 UTC, oeed commented on packages/ice/src/ice.ts
> +        address = uniq([...this.options.additionalHostAddresses, ...address]);
I initially thought that too, however this will retain the original ordering while having the additional first. But perhaps that doesn't matter?

2022-10-02 09:33 UTC, shinyoshiaki commented on packages/ice/src/ice.ts
> +        address = uniq([...this.options.additionalHostAddresses, ...address]);
> But perhaps that doesn't matter?

I think so.

2022-10-03 21:05 UTC, oeed commented on packages/ice/src/ice.ts
> +        address = uniq([...this.options.additionalHostAddresses, ...address]);
Have changed

2022-10-04 10:01 UTC, merged